Dadadsdf
KuaYueTeam/NeoKuayue pull request #5
Opened 2024-11-28 16:42 UTC by dadadsdf

实装df11g车顶
25型客车通用车底
debug

2024-11-28 18:19 UTC, MegumiKasuga commented on src/generated/resources/assets/kuayue/lang/en_us.json
> + "block.kuayue.df11g_carport_centre_fan_blind": "DF11G Centre Fan Blind",
Use "Center" instead of "Centre".
使用"center"而不是"centre".
(并不是说centre不对，而是应当统一用法)

2024-11-28 18:23 UTC, MegumiKasuga requested changes
使用"center"代替本地化文件当中的"centre"，对于注册名可不做修改(保留"centre")以减小工作量。

2024-11-29 07:58 UTC, dadadsdf reviewed
修正center

2024-11-29 23:56 UTC, MegumiKasuga approved these changes

2024-11-30 12:04 UTC, merged